[package]
name = "machinery-build"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob-match = "0.2.1"
walkdir = "2.3.3"
quote = "1.0.28"
syn = { version="2.0.16", features = ["full", "visit"]}
